# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yipzlf/Applications/cmake-3.14.1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/yipzlf/Applications/cmake-3.14.1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/yipzlf/65F33762C14D581B/Users/Lemon/Code/ComputerArchLab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/yipzlf/65F33762C14D581B/Users/Lemon/Code/ComputerArchLab

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/yipzlf/Applications/cmake-3.14.1-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/yipzlf/Applications/cmake-3.14.1-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/yipzlf/65F33762C14D581B/Users/Lemon/Code/ComputerArchLab/CMakeFiles /media/yipzlf/65F33762C14D581B/Users/Lemon/Code/ComputerArchLab/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/yipzlf/65F33762C14D581B/Users/Lemon/Code/ComputerArchLab/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

src/cpu.o: src/cpu.cpp.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/sim.o: src/sim.cpp.o

.PHONY : src/sim.o

# target to build an object file
src/sim.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/sim.cpp.o
.PHONY : src/sim.cpp.o

src/sim.i: src/sim.cpp.i

.PHONY : src/sim.i

# target to preprocess a source file
src/sim.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/sim.cpp.i
.PHONY : src/sim.cpp.i

src/sim.s: src/sim.cpp.s

.PHONY : src/sim.s

# target to generate assembly for a file
src/sim.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/sim.cpp.s
.PHONY : src/sim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... sim"
	@echo "... edit_cache"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/sim.o"
	@echo "... src/sim.i"
	@echo "... src/sim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

